version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update && apt-get install cmake
      - checkout
      - run: cmake .
      - run: make
      - run: md5sum base91 > base91.md5
      - run: ./base91 -e base91 base91.b91
      - run: mv base91 base91.bak
      - run: ./base91.bak -d base91.b91 base91
      - run: md5sum -c base91.md5
workflows:
  # Name the workflow "welcome"
  build_and_check:
    # Run the welcome/run job in its own container
    jobs:
      - build
